### PR TITLE
env-hooks: do not set RUBYOPT to load the rubygems library

### LINKED ISSUE #41: [toolchain-2.9] Invalid RUBYOPT causing further cmake errors
When building utilrb in a catkin workspace (using branch toolchain-2.9), `utilrb/env-hooks/00.utilrb.sh.in` sets RUBYOPT to `-rubygems` while it should set it to `rubygems` or `rrubygems` (`-` is implied and `ubygems` module is deprecated).

With current value it breaks ruby detection during cmake's configure stage in packages depending on both utilrb and ruby - e.g. orogen.

### PR DESCRIPTION
**Pull request by meyerj**
Fixes #41.

### CODE REVIEW

**Comment by mjbogusz** [comment]
The same deprecated flag is set in `orocos_toolchain/env.sh`, but it has been removed in its PR orocos-toolchain/orocos_toolchain#13 (just cross-referencing here)

**Comment by mjbogusz** [comment]
ping?

**Comment by JimmyDaSilva** [comment]
Please ?

**Comment by JimmyDaSilva** [comment]
Thank you @meyerj.
Tested on both Ubuntu 16.04 & 18.04

**Pull request merged**
