### PR TITLE
added OS X support; use mac ports readline instead of system readline

### PR DESCRIPTION
**Pull request by malter**

### CODE REVIEW

**Comment by doudou** [comment]
Can't that have some unintended consequences for others ... who would like for instance to use the system readline instead of the ports readline ?

**Comment by malter** [comment]
The system readline is simply to old for utilrb (the header is not compatible). I'm not sure what exactly readline does and how it is used in utilrb. Using the ports version at least solves building utilrb. If someone uses the old (system) version of redline, I would expect runtime problems.
Actually, I just figured out that the system readline is linked instead of the ports readline. I will add linking against the ports version. However, you can wait with merging until I may be able to test the OS X adaptations.

**Comment by goldhoorn** [comment]
ack for me

**Comment by doudou** [comment]
@D-Alex: how does that work on homebrew ?

**Comment by D-Alex** [comment]
This has no effect on installations running homebrew because here readline is keg-only (not installed). The reason for this is:

    Mac OS X provides similar software, and installing this software in
    parallel can cause all kinds of  trouble. OS X provides the BSD 
    libedit library, which shadows libreadline.

The best way would be to adapt utilrb to be compatible with libedit or to add an option to build without readline.

**Comment by D-Alex** [comment]
The missing functions are:
  * rl_save_prompt
  * rl_message
  * rl_readline_state
  * rl_copy_text
  * rl_replace_line
  * rl_restore_prompt

Can't we drop readline in utilrb and use gem  rb-readline for example?

**Comment by doudou** [comment]
> Can't we drop readline in utilrb and use gem rb-readline for example?

That would definitely be the smart thing to do. I'll have to find back what package is needing readline from utilrb in the first place.

**Comment by goldhoorn** [comment]
Readline is completly removed, this PR is outdated

**Pull request closed without merging**
